import 'meteor/aldeed:collection2/static'

import '../imports/api/collection/tests/CollectionTimeStamps.tests'
import '../imports/api/middleware/cors/tests/getCors.tests'
import '../imports/api/context/tests'
import '../imports/api/decorators/tests/createGetByIdRoute.tests'
import '../imports/api/decorators/tests/CRUDMethods.tests'
import '../imports/api/decorators/tests/definePublication.tests'
import '../imports/api/errors/tests/notifyAboutError.tests'
import '../imports/api/grid/tests/checkMime.tests'
import '../imports/api/grid/tests/checkUser.tests'
import '../imports/api/grid/tests/createBucket.tests'
import '../imports/api/grid/tests/createObjectId.tests'
// import '../imports/api/mixins/tests/checkPermissions.tests'
import '../imports/api/origins/tests/getAllowedOrigins.tests'
import '../imports/api/patches/tests/linkAlphaLevel.tests'
import '../imports/api/progress/tests/listsAreEqual.tests'
// import '../imports/api/progress/tests/calculateProgress.tests'
import '../imports/contexts/tests'
import '../imports/utils/tests/detectMime.tests'
