name: Test suite

on:
  push:
    branches:
      - master
      - develop
  pull_request:

jobs:
  lintcode:
    name: Javascript lint
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: setup node
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-20-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-20-

    - run: npm install
    - run: npm run lint:code
        
        # CHECKOUTS
        - name: Checkout
          uses: actions/checkout@v4

        - name: Checkout leaonline:corelib repo
          uses: actions/checkout@v4
          with:
            repository: leaonline/corelib
            path: github/corelib

        - name: Checkout leaonline:service-registry repo
          uses: actions/checkout@v4
          with:
            repository: leaonline/service-registry
            path: github/service-registry

        - name: Checkout Collection2
          uses: actions/checkout@v4
          with:
            repository: Meteor-Community-Packages/meteor-collection2
            path: github/meteor-collection2
            ref: release/v4

        # CACHING
        - name: Install Meteor
          id: cache-meteor-install
          uses: actions/cache@v4
          with:
            path: ~/.meteor
            key: v1-meteor-${{ hashFiles('.meteor/versions') }}
            restore-keys: |
              v1-meteor-

        - name: Cache NPM dependencies
          id: cache-meteor-npm
          uses: actions/cache@v4
          with:
            path: ~/.npm
            key: v1-npm-${{ hashFiles('package-lock.json') }}
            restore-keys: |
              v1-npm-

        - name: Cache Meteor build
          id: cache-meteor-build
          uses: actions/cache@v4
          with:
            path: |
              .meteor/local/resolver-result-cache.json
              .meteor/local/plugin-cache
              .meteor/local/isopacks
              .meteor/local/bundler-cache/scanner
            key: v1-meteor_build_cache-${{ github.ref }}-${{ github.sha }}
            restore-key: |
              v1-meteor_build_cache-

        - name: Setup meteor
          uses: meteorengineer/setup-meteor@v1
          with:
            meteor-release: '2.12'

        - name: Install NPM Dependencies
          run: meteor npm ci

        - name: Run Tests
          run: sh ./test.sh -c -o

        - name: Upload coverage
          uses: actions/upload-artifact@v2
          with:
            name: coverage-folder
            path: .coverage/

  coverage:
    name: Coverage report
    runs-on: ubuntu-latest
    needs: [tests]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download coverage
        uses: actions/download-artifact@v2
        with:
          name: coverage-folder
          path: .coverage/


      - name: Coverage Report
        uses: VeryGoodOpenSource/very_good_coverage@v1.1.1
        with:
          path: ".coverage/lcov.info"
          min_coverage: 65 # TODO increase to 95!

