name: Test suite

on:
  push:
    branches:
      - master
      - develop
  pull_request:

jobs:
  lintcode:
    name: Javascript lint
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: setup node
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-20-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-20-

    - run: npm install
    - run: npm run lint:code

  # uncomment when tests have been added
  tests:
    name: Meteor ${{ matrix.meteor }} tests
    runs-on: ubuntu-latest
    needs: [lintcode]
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Setup meteor
        uses: meteorengineer/setup-meteor@v1
        with:
          meteor-release: '2.12'

      - run: meteor npm install
      - run: sh ./test.sh -c -o

      - name: Upload coverage
        uses: actions/upload-artifact@v2
        with:
          name: coverage-folder
          path: .coverage/

  coverage:
    name: Coverage report
    runs-on: ubuntu-latest
    needs: [tests]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download coverage
        uses: actions/download-artifact@v2
        with:
          name: coverage-folder
          path: .coverage/


      - name: Coverage Report
        uses: VeryGoodOpenSource/very_good_coverage@v1.1.1
        with:
          path: ".coverage/lcov.info"
          min_coverage: 65 # TODO increase to 95!

